project7/app1/urls.py
from django.urls import path
from app1.views import *
app_name='aa'

urlpatterns=[
    path('pushpa/',pushpa,name='pushpa'),
]

project7/project7/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('dj/',dj,name='dj'),
]

project7/app1/models.py
from django.db import models

# Create your models here.

project7/app2/models.py
from django.db import models

# Create your models here.

project7/app1/views.py
from django.shortcuts import render

# Create your views here.
def pushpa(request):
    return render(request,'pushpa.html')

project7/app2/views.py
from django.shortcuts import render

# Create your views here.
def dj(request):
    return render(request,'dj.html')

project7/templates/dj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dj page</h1>
        <h2>
            <a href="{% url 'aa:pushpa' %}">Pushpa page</a>
        </h2>
    </center>
</body>
</html>

project7/templates/pushpa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai hello how are</h1>
        <h2><a href="{% url 'dj' %}">Travel to dj</a></h2>
    </center>
    
</body>
</html>